name: Lint frontend
on: push

jobs:
  lint-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: cd frontend && yarn install --frozen-lockfile && cd ..

      - name: Run ESLint
        run: cd frontend && yarn lint && cd ..
