name: Lint frontend
on: push

jobs:
  lint-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: cd frontend
        run: cd frontend

      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile

      - name: Build frontend
        run: yarn build

      - name: Lint frontend
        run: yarn lint && cd ..
